### ISSUE TITLE
Bluetooth mesurements, use always phone time alwais

### ISSUE THREAD

**Issue by angeld-jr2** [derdilla/blood-pressure-monitor-fl#450]
### What you want:

if the bluetooth device time is incorrect, import measurament time too. 

A option to force always phone time to bypass bad time is a nicely option.

### Why you want it:

Bad time mesuraments are invalid in all cases.

Thanks.

**Comment by derdilla** [comment]
Yes, that should really be fixed. Closing this as duplicate of #410, feel free to reopen if you think differently.
