### ISSUE TITLE
Custom export didn't include readings from today

### ISSUE THREAD

**Issue by JohnVeness** [derdilla/blood-pressure-monitor-fl#466]
### App version

1.8.1

### Bug Description

I wanted to produce a PDF of my readings for my doctor for the last 10 days, including those that I had made earlier that morning. I found I was unable to include the readings from today, just the previous 9 days.

### Steps to Reproduce

1. Settings
2. Export / Import
3. Date range: Custom
4. Pick start date
5. Pick end date (today)
6. Export format: PDF
7. EXPORT button

I thought maybe I could get it working by choosing an end date in the future, but unfortunately the UI wouldn't let me do that.

**Comment by derdilla** [comment]
Thanks for the report. Does the home page show the entries, or can you reproduce it there (if so, this might be linked to #462)?

While this is getting fixed you could probably work around the in-future-date-setting by selecting the range in the past and using the arrow buttons to move around.

**Comment by JohnVeness** [comment]
Hi, thanks. No, it's not the same as #462, as the measurements were added to the home page. It was just an export problem. Thanks for the hint about the arrows - that should hopefully workaround the problem for next time (I haven't tried yet, though).
