### ISSUE TITLE
Warn area filled without graph line

### ISSUE THREAD

**Issue by derdilla** [derdilla/blood-pressure-monitor-fl#482]
### App version

v1.8.2

### Bug Description

It looks like #468 introduced a new issue someone emailed me about. The warn area can now be filled without a graph above it.

Additionally you can see lots of cutoff/overlapped content in the graph:
- the android status bar on top
- the last measurements at the right end of the graph

![image](https://github.com/user-attachments/assets/84d56c16-285b-4828-aa0b-a417e6b3ba2a)

The graph in general looks a bit fucked up there. It was captured on a android 13 Redmi Note 11S with "Xiaomi HypeOS".

### Steps to Reproduce

The offending 2 measurements are (reduced test case):
- 103 70 70
- 98 70 70

### Details (Screenshots, Debug Info, Configurations)

<details><summary>Attachments</summary>

Another image from another Android 15 device:
![image](https://github.com/user-attachments/assets/a2942b80-4c68-4415-a113-be93c75c6f70)

</details>

**Comment by derdilla** [comment]
@Intranox, you are right, a definitely `SafeArea` won't hurt (and this screenshot makes it apparent that one is needed). When fixing this it can be fixed as well (or in another PR, the code isn't necessarily related). The point of this issue is the small red area at the top left.

**Comment by Intranox** [comment]
> @Intranox, you are right, a `SafeArea` definitely won't hurt (and this screenshot makes it apparent that one is needed). When fixing this it can be fixed as well (or in another PR, the code isn't necessarily related). The point of this issue is the small red area at the top left.

Sorry but I didn't understand well. I can only say that I have not yet encountered this problem with Android 11 on Oneplus. I would still be grateful if you can implement the SafeArea (having the notch a part of the graph is completely lost)

**Comment by derdilla** [comment]
fixed in 60fb035, 52580db
