### ISSUE TITLE
Missing measurements in PDF export file

### ISSUE THREAD

**Issue by Intranox** [derdilla/blood-pressure-monitor-fl#485]
### App version

1.8.2

### Bug Description

I am having a problem with exporting measurements to PDF, especially in the table containing the data. Some of these are missing from the output file, in particular I notice that this happens when you have to move to the next page. Between the measurement of the previous page and the one immediately after, some measurements are not printed.

### Details (Screenshots, Debug Info, Configurations)

<details><summary>Attachments</summary>

</details>

**Comment by derdilla** [comment]
Thanks, I can reproduce between 1-2 measurements missing at page transitions ([tmp.pdf](https://github.com/user-attachments/files/17901169/tmp.pdf))

<details><summary>Code to reproduce</summary>
<p>

```dart
final List<FullEntry> measurements = [
  for (int sys = 1; sys < 2000; sys++)
    (BloodPressureRecord(
      time: DateTime.now().add(Duration(minutes: sys)),
      sys: Pressure.mmHg(sys),
      dia: null,
      pul: null
    ), Note(time: DateTime.now().add(Duration(minutes: sys))), []),
];
final pdf = await PdfConverter(
  PdfExportSettings(),
  await AppLocalizations.delegate.load(const Locale('en')),
  Settings(),
  ExportColumnsManager(),
).create(measurements);
File('tmp.pdf').writeAsBytesSync(pdf);
```

</p>
</details>
